### PR TITLE
castling rights on rook capture. closes nvzqz/Sage#8

### PR DESCRIPTION
**Pull request by santhosbaala**

### CODE REVIEW

**Comment by nvzqz** [comment]
This does not restore rook castling rights if the capture is undone.

Also, the `if let _ = capture?.kind.isRook {` part passes for any capture. Instead do:
```swift
if let capture = capture, capture.kind.isRook {
    ...
}
```

**Comment by santhosbaala** [comment]
Made the change with `if let ..`. `_undoMove` seems to already restore the castling rights. What do you mean by undoing the capture?

**Comment by nvzqz** [comment]
Sorry, I should've specified. It's been a while since I looked through the code for the project. You're right. I forgot that castling rights were retained in history.

**Comment by santhosbaala** [comment]
Done, build passing now!

**Pull request merged**
